[build]
  command = "npm run build"
  publish = "dist"
  node_version = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyCgbi3aimcJNHng4N9o2-YIf7ODhVbz2P8"
  VITE_FIREBASE_AUTH_DOMAIN = "taskmates7.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "taskmates7"
  VITE_FIREBASE_STORAGE_BUCKET = "taskmates7.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "79003234750"
  VITE_FIREBASE_APP_ID = "1:79003234750:web:553567c3670d4d864809ef"
  VITE_FIREBASE_MEASUREMENT_ID = "G-HMPG88T3CQ"
  VITE_RAZORPAY_KEY_ID = "your_razorpay_key_id"