name: taskmates
description: TaskMates - Get Things Done with Trusted Professionals
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_analytics: ^10.7.4
  firebase_messaging: ^14.7.9
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.5
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  intl: ^0.18.1
  razorpay_flutter: ^1.3.5
  url_launcher: ^6.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/