backend:
  name: github
  repo: dheerajpullarevu/taskmates
  branch: main
  base_url: https://api.netlify.com

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "tasks"
    label: "Tasks"
    folder: "content/tasks"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Category", name: "category", widget: "select", options: ["online", "offline", "specialized"]}
      - {label: "Priority", name: "priority", widget: "select", options: ["low", "medium", "high", "urgent"]}
      - {label: "Budget", name: "budget", widget: "number"}
      - {label: "Deadline", name: "deadline", widget: "datetime"}
      - {label: "Skills Required", name: "skills", widget: "list"}
      - {label: "Location", name: "location", widget: "object", fields: [
          {label: "Address", name: "address", widget: "string"},
          {label: "Latitude", name: "latitude", widget: "number"},
          {label: "Longitude", name: "longitude", widget: "number"}
        ], required: false}

  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Icon", name: "icon", widget: "string"}
      - {label: "Color", name: "color", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Active", name: "isActive", widget: "boolean", default: true}